spring:
  application:
    name: kopic-ws
  profiles:
    default: local

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
